version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3302:3302"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3303:3303"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

